page_margin:
  top_margin: 90
  right_margin: 80
  bottom_margin: 40
  left_margin: 30

wrap_width: 110

table:
  row_height: 10
  col_width: 130
  font_size: 8
  font_name: 'Yekan'
  alignment: 'CENTER'

participant_p_line: 3

space:
  width: 1
  height: 10

signature:
  width: 100
  height: 100
