# Generated by Django 5.0.6 on 2024-07-30 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_no", models.CharField(max_length=10, unique=True)),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("کارمند", "کارمند"), ("هیات علمی", "هیات علمی")],
                        default="کارمند",
                        max_length=20,
                    ),
                ),
                ("dep", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResolutionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolution_type", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_name", models.CharField(max_length=255)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("روزانه", "روزانه"),
                            ("هفتگی", "هفتگی"),
                            ("دوهفتگی", "هفتگی"),
                            ("ماهیانه", "ماهیانه"),
                            ("غیرمشخص", "غیرمشخص"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("عضو", "عضو"), ("دبیر", "دبیر")], max_length=64
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.employee",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.meeting",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meeting",
            name="members",
            field=models.ManyToManyField(
                through="meeting.Membership", to="meeting.employee"
            ),
        ),
        migrations.CreateModel(
            name="Proceeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proceeding_no", models.CharField(max_length=255)),
                ("pdate", models.DateField()),
                ("ptime", models.TimeField(blank=True, null=True)),
                ("loc", models.CharField(blank=True, max_length=255, null=True)),
                ("readonly", models.BooleanField(default=False)),
                ("upload", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.meeting",
                    ),
                ),
                ("participants", models.ManyToManyField(to="meeting.employee")),
            ],
        ),
        migrations.CreateModel(
            name="Stockholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "مرد"), ("F", "زن")], default="M", max_length=1
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "national_id",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("mobile", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_no", models.CharField(max_length=64)),
                ("act_text", models.CharField(max_length=255)),
                (
                    "resolution_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("result", models.BooleanField(default=True)),
                (
                    "stockholder_type",
                    models.CharField(
                        choices=[("دانشجو", "دانشجو"), ("کارکنان", "کارکنان")],
                        max_length=64,
                    ),
                ),
                (
                    "proceeding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.proceeding",
                    ),
                ),
                (
                    "stockholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.stockholder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="stockholder",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="meeting.stockholder"
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stdno", models.CharField(max_length=10, unique=True)),
                ("major", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "maghta",
                    models.CharField(
                        choices=[
                            ("کارشناسی", "کارشناسی"),
                            ("کارشناسی ارشد", "کارشناسی ارشد"),
                            ("دکتری", "دکتری"),
                        ],
                        default="کارشناسی",
                        max_length=20,
                    ),
                ),
                (
                    "stockholder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.stockholder",
                    ),
                ),
            ],
        ),
    ]
