# Generated by Django 5.0.7 on 2024-08-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockholder",
            name="signature",
            field=models.FileField(
                blank=True, max_length=254, null=True, upload_to="signatures/"
            ),
        ),
    ]
