# Generated by Django 5.0.7 on 2024-08-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0002_stockholder_signature"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="invite_reason",
            new_name="is_signed",
        ),
    ]
