# Generated by Django 5.0.7 on 2024-08-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0003_rename_invite_reason_participant_is_signed"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("proceeding", "member")},
        ),
    ]
