# Generated by Django 5.0.7 on 2024-08-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0004_alter_participant_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resolution",
            name="stockholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meeting.stockholder",
            ),
        ),
        migrations.AlterField(
            model_name="resolution",
            name="stockholder_type",
            field=models.CharField(
                blank=True,
                choices=[("دانشجو", "دانشجو"), ("کارکنان", "کارکنان")],
                max_length=64,
                null=True,
            ),
        ),
    ]
