# Generated by Django 5.0.7 on 2024-08-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0005_alter_resolution_stockholder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resolution",
            name="stockholder_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "انتخاب کنید"),
                    ("دانشجو", "دانشجو"),
                    ("کارکنان", "کارکنان"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
